#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x08302DB6A2670428 (tim.ruehsen@gmx.de)
#
Name     : wget
Version  : 1.20.1
Release  : 38
URL      : https://mirrors.kernel.org/gnu/wget/wget-1.20.1.tar.gz
Source0  : https://mirrors.kernel.org/gnu/wget/wget-1.20.1.tar.gz
Source99 : https://mirrors.kernel.org/gnu/wget/wget-1.20.1.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: wget-bin = %{version}-%{release}
Requires: wget-license = %{version}-%{release}
Requires: wget-locales = %{version}-%{release}
Requires: wget-man = %{version}-%{release}
BuildRequires : flex
BuildRequires : glibc-locale
BuildRequires : perl
BuildRequires : perl(HTTP::Daemon)
BuildRequires : perl(HTTP::Date)
BuildRequires : perl(HTTP::Request)
BuildRequires : perl(IO::Socket::SSL)
BuildRequires : perl(LWP::MediaTypes)
BuildRequires : perl(Net::SSLeay)
BuildRequires : perl(URI)
BuildRequires : pkgconfig(libpcre)
BuildRequires : pkgconfig(libpcre2-8)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(zlib)
BuildRequires : texinfo

%description
GNU Wget
========
Current Web home: https://www.gnu.org/software/wget/
GNU Wget is a free utility for non-interactive download of files from
the Web.  It supports HTTP, HTTPS, and FTP protocols, as well as
retrieval through HTTP proxies.

%package bin
Summary: bin components for the wget package.
Group: Binaries
Requires: wget-license = %{version}-%{release}
Requires: wget-man = %{version}-%{release}

%description bin
bin components for the wget package.


%package doc
Summary: doc components for the wget package.
Group: Documentation
Requires: wget-man = %{version}-%{release}

%description doc
doc components for the wget package.


%package license
Summary: license components for the wget package.
Group: Default

%description license
license components for the wget package.


%package locales
Summary: locales components for the wget package.
Group: Default

%description locales
locales components for the wget package.


%package man
Summary: man components for the wget package.
Group: Default

%description man
man components for the wget package.


%prep
%setup -q -n wget-1.20.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545861221
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --with-ssl=openssl --disable-psl --disable-ntlm
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1545861221
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/wget
cp COPYING %{buildroot}/usr/share/package-licenses/wget/COPYING
%make_install
%find_lang wget

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wget

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/info/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/wget/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/wget.1

%files locales -f wget.lang
%defattr(-,root,root,-)

