#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x08302DB6A2670428 (tim.ruehsen@gmx.de)
#
Name     : wget
Version  : 1.19.5
Release  : 33
URL      : https://mirrors.kernel.org/gnu/wget/wget-1.19.5.tar.gz
Source0  : https://mirrors.kernel.org/gnu/wget/wget-1.19.5.tar.gz
Source99 : https://mirrors.kernel.org/gnu/wget/wget-1.19.5.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: wget-bin
Requires: wget-doc
Requires: wget-locales
BuildRequires : flex
BuildRequires : perl(HTTP::Daemon)
BuildRequires : perl(HTTP::Date)
BuildRequires : perl(HTTP::Request)
BuildRequires : perl(IO::Socket::SSL)
BuildRequires : perl(LWP::MediaTypes)
BuildRequires : perl(Net::SSLeay)
BuildRequires : perl(URI)
BuildRequires : pkgconfig(libpcre)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(zlib)
BuildRequires : texinfo

%description
GNU Wget
========
Current Web home: https://www.gnu.org/software/wget/
GNU Wget is a free utility for non-interactive download of files from
the Web.  It supports HTTP, HTTPS, and FTP protocols, as well as
retrieval through HTTP proxies.

%package bin
Summary: bin components for the wget package.
Group: Binaries

%description bin
bin components for the wget package.


%package doc
Summary: doc components for the wget package.
Group: Documentation

%description doc
doc components for the wget package.


%package locales
Summary: locales components for the wget package.
Group: Default

%description locales
locales components for the wget package.


%prep
%setup -q -n wget-1.19.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1526921433
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --with-ssl=openssl --disable-psl --disable-ntlm
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1526921433
rm -rf %{buildroot}
%make_install
%find_lang wget

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wget

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*

%files locales -f wget.lang
%defattr(-,root,root,-)

