#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v4
# autospec commit: 1ab68ca
#
# Source0 file verified with key 0x64FF90AAE8C70AF9 (darnir@gnu.org)
#
Name     : wget
Version  : 1.24.5
Release  : 52
URL      : https://mirrors.kernel.org/gnu/wget/wget-1.24.5.tar.gz
Source0  : https://mirrors.kernel.org/gnu/wget/wget-1.24.5.tar.gz
Source1  : https://mirrors.kernel.org/gnu/wget/wget-1.24.5.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: wget-bin = %{version}-%{release}
Requires: wget-info = %{version}-%{release}
Requires: wget-license = %{version}-%{release}
Requires: wget-locales = %{version}-%{release}
Requires: wget-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : flex
BuildRequires : glibc-locale
BuildRequires : libpsl-dev
BuildRequires : libunistring-dev
BuildRequires : perl
BuildRequires : perl(HTTP::Daemon)
BuildRequires : perl(HTTP::Date)
BuildRequires : perl(HTTP::Request)
BuildRequires : perl(IO::Socket::SSL)
BuildRequires : perl(LWP::MediaTypes)
BuildRequires : perl(Net::SSLeay)
BuildRequires : perl(URI)
BuildRequires : pkgconfig(libidn2)
BuildRequires : pkgconfig(libpcre)
BuildRequires : pkgconfig(libpcre2-8)
BuildRequires : pkgconfig(libproxy-1.0)
BuildRequires : pkgconfig(nettle)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(zlib)
BuildRequires : texinfo
BuildRequires : util-linux-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
GNU Wget
========
Current Web home: https://www.gnu.org/software/wget/
GNU Wget is a free utility for non-interactive download of files from
the Web.  It supports HTTP, HTTPS, and FTP protocols, as well as
retrieval through HTTP proxies.

%package bin
Summary: bin components for the wget package.
Group: Binaries
Requires: wget-license = %{version}-%{release}

%description bin
bin components for the wget package.


%package info
Summary: info components for the wget package.
Group: Default

%description info
info components for the wget package.


%package license
Summary: license components for the wget package.
Group: Default

%description license
license components for the wget package.


%package locales
Summary: locales components for the wget package.
Group: Default

%description locales
locales components for the wget package.


%package man
Summary: man components for the wget package.
Group: Default

%description man
man components for the wget package.


%prep
%setup -q -n wget-1.24.5
cd %{_builddir}/wget-1.24.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710170790
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --with-ssl=openssl \
--disable-psl \
--disable-ntlm \
--disable-iri
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1710170790
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/wget
cp %{_builddir}/wget-%{version}/COPYING %{buildroot}/usr/share/package-licenses/wget/a927edd8b08a22998fb03ef3675387d0071f8d82 || :
export GOAMD64=v2
GOAMD64=v2
%make_install
%find_lang wget-gnulib
%find_lang wget

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wget

%files info
%defattr(0644,root,root,0755)
/usr/share/info/wget.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/wget/a927edd8b08a22998fb03ef3675387d0071f8d82

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/wget.1

%files locales -f wget-gnulib.lang -f wget.lang
%defattr(-,root,root,-)

